
#ifndef PARSE_H
#define PARSE_H

#include <map>
#include <set>

#include "CLI11.hpp"

namespace bench {
struct Args {
  std::map<std::string, std::string> PreFileMap{
      {"dota", "/home/masitan/gfe_system/gfe_data/dota-league.e"},
      {"dota-league", "/home/masitan/gfe_system/gfe_data/dota-league.e"},
      {"graph24",
       "/home/masitan/gfe_system/gfe_data/graph500-24/graph500-24.e"},
      {"datagen-8_4-fb",
       "/home/masitan/gfe_system/gfe_data/datagen-8_4-fb.e"},
      {"datagen-7_9-fb",
       "/home/masitan/gfe_system/gfe_data/datagen-7_9-fb.e"},
      {"datagen-8_4-fb-weighted",
       "/home/masitan/gfe_system/gfe_data/datagen-8_4-fb-weighted.e"},
      {"wiki-Talk", "/home/masitan/gfe_system/gfe_data/wiki-Talk.e"},
      {"edit-enwiki",
       "/home/masitan/gfe_system/gfe_data/edit-enwiki.e"}};
  CLI::App app{"AVB Test Program"};

  bool read_test = false;
  bool con_wr_test = false;
  bool reference_schedule_ = false;
  bool churn_ = false;
  bool split_update_ = false;
  bool teseo_churn_ = false;
  bool single_read_work = false;

  bool file_input = false;
  bool permute_ = false;
  bool permute_explicit_ = false;
  bool check_ = false;
  std::string input_file = "";
  std::string graphlog_ = "";
  std::string algorithm_ = "";
  std::string system_ = "";
  unsigned limit_edge_nums = 0;
  int Spruce_wt = 64;
  int read_thread = 64;
  int root = 0;
  bool root_explicit_ = false;
  std::vector<std::string> read_tasks;  // Algorithms assigned to concurrent reader tasks.
  int repeat_count = 1;                 // Number of input-edge passes.

  // Experiment 1: Mixed-update.
  std::string mix_ = "";      // --mix id|idm|m100; empty selects the ordinary write path.
  int rounds_ = 5;            // --rounds: number of mixed-update rounds.
  bool rounds_explicit_ = false;
  bool stall_abort_ = false;  // --stall-abort: raise SIGABRT on STALL to produce a core dump.
  uint64_t wseed_ = 42;       // --wseed: reproducible workload seed.

  // Experiment 2: HotSet update.
  double hotset_ = 0.0;  // --hotset: hot-edge fraction of the original graph; zero disables it.
  std::string hotset_file_ = "";  // --hotset-file: candidate hot edges generated by vertex-degree sampling.
  int hotset_update_pct_ = 100;  // --hotset-update-pct: update transaction percentage in mixed HotSet writes.
  // --progress-file: periodically write concurrent progress to a sidecar so runners
  // can recover partial throughput/latency after a crash or timeout; omitted means no extra thread.
  std::string progress_file_ = "";

  bool gen_and_output = false;

  // Graphalytics-like static evaluation. This is intentionally separate from
  // --repeat, which keeps its existing edge-amplification meaning.
  bool graphalytics_ = false;
  int repetitions_ = 1;
  int pr_iterations_ = 10;
  double pr_damping_ = 0.85;
  int cdlp_iterations_ = 10;
  std::string output_file_ = "";
  std::string edge_mode_ = "undirected";
  bool common_algorithms_ = false;  // Opt-in shared Graphalytics kernels for all six algorithms.

  // --quiet suppresses per-execution progress/reader logs during timed runs
  // to avoid stdout affecting wall-clock throughput; use --verbose for diagnostic output.
  bool quiet_ = true;
  // --no-collect-results disables copying algorithm output into last_result_
  // in backend Run* methods so processing_ms reflects algorithm time without result collection.
  // Result collection is enabled by default.
  bool collect_results_ = true;

  void ParseArgs(int argc, char** argv);

  bool IsFileInput() { return file_input; }
  bool TouchLimitEdgeNum(unsigned edge_num) {
    return limit_edge_nums == edge_num;
  }
};
}  // namespace bench
#endif  // PARSE_H
